<?php
/**
 * DO NOT EDIT THIS FILE
 */
define('APPDIR', $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR);
//get the structure file and pass to class
require APPDIR . "setup.php";

$tp = new Template($structure);

require "templates/html.php";
